version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing required tools..."
      - yum install -y jq
      - echo "Build environment ready."

  pre_build:
    commands:
      - |
        TF_ORG_NAME=$(aws ssm get-parameter --name "/aft/config/terraform/org-name" --query "Parameter.Value" --output text)
        TF_TOKEN=$(aws ssm get-parameter --name "/aft/config/terraform/token" --with-decryption --query "Parameter.Value" --output text)
        TF_ENDPOINT=$(aws ssm get-parameter --name "/aft/config/terraform/api-endpoint" --query "Parameter.Value" --output text)
        TF_WORKSPACE_NAME=$(aws ssm get-parameter --name "/aft/config/terraform/scp-workspace-name" --query "Parameter.Value" --output text)
        TF_PROJECT_NAME=$(aws ssm get-parameter --name "/aft/config/terraform/project-name" --query "Parameter.Value" --output text)
        TF_CONFIG_PATH="./temp_configuration_file.tar.gz"

  build:
    commands:
      - echo "Triggering Terraform Enterprise run..."
      - |
        PAYLOAD=$(jq -n \
          --arg message "Triggered by AFT" \
          --arg workspace "$TF_WORKSPACE_NAME" \
          '{data: {attributes: {message: $message}, type: "runs", relationships: {workspace: {data: {type: "workspaces", id: $workspace}}}}}')
        curl -X POST \
          --url "${TF_ENDPOINT}/runs" \
          --header "Authorization: Bearer $TF_TOKEN" \
          --header "Content-Type: application/vnd.api+json" \
          --data "$PAYLOAD"

artifacts:
  files:
    - "**/*"
  discard-paths: no
